name: build
on:
 workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'staging'
jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: "scripts/go.mod"

      - name: Build release archive
        run: |
          echo "Building Grafana Dashboards, Prometheus Rules and Alerts"
          make
          echo "Compressing Artifacts"
          zip -r kubernetes-mixin-${{ github.ref_name }}.zip dashboards_out prometheus_alerts.yaml prometheus_rules.yaml
      - name: Display structure of downloaded files
        run: ls -R  
        
      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: kubernetes-mixin-${{ github.ref_name }}.zip
          path: ./

